# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: build docker image and deploy to Jelastic staging environement

on:
  push:
    branches: ['MY_BRANCH'] # TODO: change this to the branch that needs to be deployed (ex: staging or production)

jobs:
  build-and-push-image:
    uses: Marvelous-Digital/.github/workflow-templates/jelastic/build-and-push-to-registry.yml@master
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      DOPPLER_TOKEN_RUN: ${{ secrets.DOPPLER_TOKEN_RUN }}
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REGISTRY: ghcr.io
      GITHUB_ACTOR: ${{ github.actor }}
    with:
      environment: MY_ENVIRONEMENT # TODO: change this
      image_name: ${{ github.repository }}
  redeploy-and-notify:
    needs: build-and-push-image
    uses: Marvelous-Digital/.github/workflow-templates/jelastic/deploy-and-notify.yml@master
    secrets:
      JELASTIC_USERNAME: ${{ secrets.JELASTIC_USERNAME }}
      JELASTIC_TOKEN: ${{ secrets.JELASTIC_TOKEN }}
    with:
      environment: MY_ENVIRONEMENT # TODO: change this