# Requied variables in order for this workflow to work
#
# environment:
# - create an environement for your branch MY_BRANCH in github in order to have multiple deploy scripts with different variables
# vars:
# - WEBSITE_DIRECTORY (environement): home of the website on the server from the root (ex: sites/my-website.com/)
# - CHAT_KEY (organisation): google space api key. (for Marvelous-Digital, this value is already set at an organisation level, but can be overriden at a repo level if needed)
#
# secrets:
# - MRVLS_PRIVATE_REPO_KEY (organisation): for Marvelous-Digital, this value is already on the orgs repo
# - COMPOSER_AUTH_JSON (repositiory): the content of the auth.json
# - SSH_HOST (repositiory): the host of the ssh server
# - SSH_USER (repositiory): the user of the ssh connection
# - SSH_PASSWORD (repositiory): the ssh users password
# - SSH_PORT (repositiory): the port of the ssh connection
#


name: Deploy a laravel application on a standard host using ssh

on:
  push:
    branches: ["MY_BRANCH"] # TODO: change this to the branch that needs to be deployed (ex: staging or production)

env:
  WEBSITE_DIRECTORY: ${{ vars.WEBSITE_DIRECTORY }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: "MY_ENVIRONEMENT"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"
          ssh-key: ${{ secrets.MRVLS_PRIVATE_REPO_KEY }}
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          version: "2.6.6"
          args: "--no-scripts"
          php_extensions: intl exif imagick bcmath gd zip
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "*, !**/.git*, !**/.git*/**, !vendor/**, !**/node_modules/**, !storage/framework/cache/**, !public/hot"
          target: ${{ env.WEBSITE_DIRECTORY }}
      - name: Composer install over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: "cd ${{ env.WEBSITE_DIRECTORY }} && sh run.sh ${{ env.WEBSITE_DIRECTORY }}" # TODO: change the run script if different
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: "${{ vars.CHAT_KEY }}"
          status: ${{ job.status }}
        if: always()
