name: build docker image and deploy to Jelastic staging environement

on:
  push:
    branches: ['staging']

jobs:
  build-and-push-image:
    uses: Marvelous-Digital/.github/workflow-templates/jelastic/build-and-push-to-registry.yml@master
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      DOPPLER_TOKEN_RUN: ${{ secrets.DOPPLER_TOKEN_RUN }}
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REGISTRY: ghcr.io
      GITHUB_ACTOR: ${{ github.actor }}
    with:
      environment: staging
      image_name: ${{ github.repository }}
  redeploy-and-notify:
    needs: build-and-push-image
    uses: Marvelous-Digital/.github/workflow-templates/jelastic/deploy-and-notify.yml@master
    secrets:
      JELASTIC_USERNAME: ${{ secrets.JELASTIC_USERNAME }}
      JELASTIC_TOKEN: ${{ secrets.JELASTIC_TOKEN }}
    with:
      environment: staging
